GET http://localhost:3003/api/patients/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFzdGVyIEFkbWluIiwiaWQiOiI2YTgzYjQyNjNmNmYwMzQ2NmZjMGVjMjUiLCJyb2xlIjoibWFzdGVyIiwiaWF0IjoxNzkxMDMxNjEyLCJleHAiOjE3OTEwMzUyMTJ9.ncZlC7lhqh6ToX1MVHSNUbD_bsiJzFAZdyIo3SUfoPI


###

POST http://localhost:3003/api/patients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFzdGVyIEFkbWluIiwiaWQiOiI2YTgzYjQyNjNmNmYwMzQ2NmZjMGVjMjUiLCJyb2xlIjoibWFzdGVyIiwiaWF0IjoxNzkxMDMxNjEyLCJleHAiOjE3OTEwMzUyMTJ9.ncZlC7lhqh6ToX1MVHSNUbD_bsiJzFAZdyIo3SUfoPI

{"name": "John McClane",
    "dateOfBirth": "1986-07-09",
    "gender": "male",
    "occupation": "New york city cop"}

###
POST http://localhost:3003/api/patients/6ac0f9dd575444ac29db7335/entries
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFzdGVyIEFkbWluIiwiaWQiOiI2YTgzYjQyNjNmNmYwMzQ2NmZjMGVjMjUiLCJyb2xlIjoibWFzdGVyIiwiaWF0IjoxNzkxMDMxNjEyLCJleHAiOjE3OTEwMzUyMTJ9.ncZlC7lhqh6ToX1MVHSNUbD_bsiJzFAZdyIo3SUfoPI

{
  "id": "inp-entry-002",
  "date": "2026-03-12",
  "specialist": "Dr. Michael Chen",
  "description": "Admitted via A&E for acute appendicitis, underwent laparoscopic appendectomy.",
  "type": "Inpatient",
  "admissionDate": "2026-03-12",
 "admissionReason": "Acute lower right quadrant abdominal pain, fever, and leukocytosis.",
  "dischargeDate": "2026-03-14",
  "ward": "5A Surgical Ward",
  "bedNumber": "B12",
  "dischargeSummary": "Unremarkable postoperative recovery. Surgical wound clean and dry.",
  "dischargeStatus": "Stable / Discharged Home",
  "followUpInstruction": "SOPD follow-up in 2 weeks for wound inspection and pathology report.",
  "diagnosisCodes": ["K35.80", "Z98.89"]
}

###
DELETE  http://localhost:3003/api/patients/6aa097773377ec852bbfb61a/entries/6aa097873377ec852bbfb61b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFzdGVyIEFkbWluIiwiaWQiOiI2YTgzYjQyNjNmNmYwMzQ2NmZjMGVjMjUiLCJyb2xlIjoibWFzdGVyIiwiaWF0IjoxNzg4OTA5MTg0LCJleHAiOjE3ODg5MTI3ODR9.Y0X0lwbO81Lzvt4OYiVZUSsaAYHyrKZxluUtCfJXvsA

###
DELETE http://localhost:3003/api/patients/6aa095c73377ec852bbfb615
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFzdGVyIEFkbWluIiwiaWQiOiI2YTgzYjQyNjNmNmYwMzQ2NmZjMGVjMjUiLCJyb2xlIjoibWFzdGVyIiwiaWF0IjoxNzkxMDMxNjEyLCJleHAiOjE3OTEwMzUyMTJ9.ncZlC7lhqh6ToX1MVHSNUbD_bsiJzFAZdyIo3SUfoPI

###

###
GET http://localhost:3003/api/diagnoses